### NumPy: arrays, operations, broadcasting
### Matrix Operations with NumPy

# Create Numpy arrays
### np.array()
### np.zeros/ones/empty/random()
### np.arrange()
### np.linspace()
### Copy()
### Identity()

In [2]:
import numpy as np

In [2]:
n1 = np.array([1, 2, 3])
n1

array([1, 2, 3])

In [3]:
n2 = np.array([
    [4, 5, 6], [7, 8, 9],
])
n2

array([[4, 5, 6],
       [7, 8, 9]])

In [4]:
n3 = np.zeros((3, 4))
n3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
n4 = np.ones((3, 4))
n4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
n5 = np.identity(4)
n5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
n6 = np.arange(10, 30, 2)
n6

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [21]:
n7 = np.linspace(10, 30, 10)
n7

array([10.        , 12.22222222, 14.44444444, 16.66666667, 18.88888889,
       21.11111111, 23.33333333, 25.55555556, 27.77777778, 30.        ])

# Propoerties and attributes
### shape
### nDim
### size
### itemsize
### dtype
### astype()

In [60]:
arr1 = np.array([
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
    ],
    [
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]],
        [[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]
    ]
], dtype=np.float64)

In [61]:
arr1

array([[[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]],


       [[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]]])

In [62]:
arr1.shape

(2, 2, 4, 3)

In [63]:
arr1.ndim

4

In [64]:
arr1.size

48

In [65]:
arr1.itemsize

8

In [66]:
arr1.dtype

dtype('float64')

In [70]:
arr1 = arr1.astype(dtype=np.int8)

In [71]:
arr1.dtype

dtype('int8')

# Lists vs Arrays

# Indexing slicing and iterations

In [73]:
arr2 = np.arange(24)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [77]:
arr2 = arr2.reshape(3, 8)
arr2

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [80]:
arr2 =arr2.reshape(3, 2, 4)
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [84]:
arr2[1][1][2]

np.int64(14)

In [87]:
arr2[2][1][3]

np.int64(23)

In [110]:
arr2[::1,:1:1,:1:1]

array([[[ 0]],

       [[ 8]],

       [[16]]])

In [133]:
arr2[1:2,:,1:3]

array([[[ 9, 10],
        [13, 14]]])

In [136]:
arr2[:,:,1]

array([[ 1,  5],
       [ 9, 13],
       [17, 21]])

In [149]:
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [157]:
arr2[0:1,1:2,1:3]

array([[[5, 6]]])

In [159]:
arr2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [171]:
arr2[:,0:2:2, 1:2]

array([[[ 1]],

       [[ 9]],

       [[17]]])

In [158]:
for i in np.nditer(arr2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [7]:
arr2 = np.array([
    [
        [
            [
                [0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]
            ],
            [
                [12, 13, 14],
                [15, 16, 17],
                [18, 19, 20],
                [21, 22, 23]
            ]
        ],
        [
            [
                [24, 25, 26],
                [27, 28, 29],
                [30, 31, 32],
                [33, 34, 35]
            ],
            [
                [36, 37, 38],
                [39, 40, 41],
                [42, 43, 44],
                [45, 46, 47]
            ]
        ]
    ],
    [
        [
            [
                [48, 49, 50],
                [51, 52, 53],
                [54, 55, 56],
                [57, 58, 59]
            ],
            [
                [60, 61, 62],
                [63, 64, 65],
                [66, 67, 68],
                [69, 70, 71]
            ]
        ],
        [
            [
                [72, 73, 74],
                [75, 76, 77],
                [78, 79, 80],
                [81, 82, 83]
            ],
            [
                [84, 85, 86],
                [87, 88, 89],
                [90, 91, 92],
                [93, 94, 95]
            ]
        ]
    ]
], dtype=np.float64)

In [4]:
arr2

array([[[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]],

         [[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]]],


        [[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]],

         [[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]]]],



       [[[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]],

         [[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]]],


        [[[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]],

         [[ 1.,  2.,  3.],
          [ 4.,  5.,  6.],
          [ 7.,  8.,  9.],
          [10., 11., 12.]]]]])

In [8]:
arr2.shape

(2, 2, 2, 4, 3)

In [19]:
arr2[1:2, 1:, 0:1, 2:, 1:2]

array([[[[[79.],
          [82.]]]]])

In [28]:
aar3 = arr2.reshape(96)

In [29]:
aar3

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51.,
       52., 53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64.,
       65., 66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77.,
       78., 79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90.,
       91., 92., 93., 94., 95.])

In [30]:
aar4 = arr2.copy()

In [31]:
aar4

array([[[[[ 0.,  1.,  2.],
          [ 3.,  4.,  5.],
          [ 6.,  7.,  8.],
          [ 9., 10., 11.]],

         [[12., 13., 14.],
          [15., 16., 17.],
          [18., 19., 20.],
          [21., 22., 23.]]],


        [[[24., 25., 26.],
          [27., 28., 29.],
          [30., 31., 32.],
          [33., 34., 35.]],

         [[36., 37., 38.],
          [39., 40., 41.],
          [42., 43., 44.],
          [45., 46., 47.]]]],



       [[[[48., 49., 50.],
          [51., 52., 53.],
          [54., 55., 56.],
          [57., 58., 59.]],

         [[60., 61., 62.],
          [63., 64., 65.],
          [66., 67., 68.],
          [69., 70., 71.]]],


        [[[72., 73., 74.],
          [75., 76., 77.],
          [78., 79., 80.],
          [81., 82., 83.]],

         [[84., 85., 86.],
          [87., 88., 89.],
          [90., 91., 92.],
          [93., 94., 95.]]]]])

In [39]:
ar5 = aar4[0]
ar5.shape

(2, 2, 4, 3)

In [40]:
aar4.squeeze(axis=0)

ValueError: cannot select an axis to squeeze out which has size not equal to one

In [43]:
x = np.arange(24).reshape(1, 2, 3, 4)
x

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [44]:
x.shape

(1, 2, 3, 4)

In [47]:
y = x.squeeze(axis=0)
y


array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [48]:
y.shape

(2, 3, 4)

In [49]:
z = y.reshape(1, 2, 3, 4)
z

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]]])

In [50]:
z.shape

(1, 2, 3, 4)

# Numpy Operations

In [112]:
r1 = np.arange(24).reshape(1, 2, 1, 3, 4) # 72
r2 = np.arange(24).reshape(2, 1, 1, 4, 3) # 72

In [113]:
r1

array([[[[[ 0,  1,  2,  3],
          [ 4,  5,  6,  7],
          [ 8,  9, 10, 11]]],


        [[[12, 13, 14, 15],
          [16, 17, 18, 19],
          [20, 21, 22, 23]]]]])

In [114]:
r2

array([[[[[ 0,  1,  2],
          [ 3,  4,  5],
          [ 6,  7,  8],
          [ 9, 10, 11]]]],



       [[[[12, 13, 14],
          [15, 16, 17],
          [18, 19, 20],
          [21, 22, 23]]]]])

In [115]:
r3 = r1 @ r2

In [116]:
r3

array([[[[[  42,   48,   54],
          [ 114,  136,  158],
          [ 186,  224,  262]]],


        [[[ 258,  312,  366],
          [ 330,  400,  470],
          [ 402,  488,  574]]]],



       [[[[ 114,  120,  126],
          [ 378,  400,  422],
          [ 642,  680,  718]]],


        [[[ 906,  960, 1014],
          [1170, 1240, 1310],
          [1434, 1520, 1606]]]]])

In [117]:
r3.shape

(2, 2, 1, 3, 3)

In [119]:
r3.max(axis=1)

array([[[[ 258,  312,  366],
         [ 330,  400,  470],
         [ 402,  488,  574]]],


       [[[ 906,  960, 1014],
         [1170, 1240, 1310],
         [1434, 1520, 1606]]]])